Hello microverse full project
Gatofrances123/Hello-Microverse pull request #1
Opened 2023-06-06 17:04 UTC by Gatofrances123

## This pull request includes : 
1. html and styles css 
2. git ignore files 
3. linters configurations 
4. documented my repository professional

2023-06-06 23:14 UTC, ademibowale requested changes
## STATUS: Changes Required :recycle:

### Hi @Gatofrances123  , 👋 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.tenor.com/isiLRnxz3zwAAAAM/cat-driving-serious.gif" width="500px" height="300px">

### To Highlight 🥇

✅ Descriptive Pull Request title and summary. ✔️
✅ Good use of Github flow ✔️
✅All linters are checked.
✅Project is professionally documented.
✅The right GitHub flow method has been used.
✅Professional pull request title and description.

### Changes Required

- [x]  _Please check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @Adebowale ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-06 23:14 UTC, ademibowale commented on LICENSE
> +Copyright (c) [year] [fullname]
- [ ] kindly edit this license template ,include your full name and year this will show a professional Mit lincense readme.

2023-06-06 23:14 UTC, ademibowale commented on README.md
> +- git packages
- [ ] I can see that you are missing some sections 
- [ ] Professional readme '

2023-06-07 03:01 UTC, Gatofrances123 commented on README.md
> +- git packages
Hello! but I don't know how to fill out this information, can you give me some guidance?

2023-06-07 03:15 UTC, Gatofrances123 commented on LICENSE
> +Copyright (c) [year] [fullname]
Hello, I'm sorry, I don't understand how to do this, can you explain me please?

2023-06-07 05:23 UTC, ademibowale commented on LICENSE
> +Copyright (c) [year] [fullname]
Oh I see kindly go into your project requirement read through you will see link for readme file click the link you see the Microverse readme setup ,then copy the readme template and fill all the sections accordingly.

2023-06-07 16:46 UTC, Gatofrances123 commented on README.md
> +- git packages
Hello! can you explain me not only with the example of how to fill each space please? There are some spaces that I don't understand how they should go.

2023-06-08 16:54 UTC, closed without merging